### PR TITLE
cli: add-bank-with-seed command

### PR DESCRIPTION
**Pull request by exdx**
Adds a new CLI command to exercise the functionality added in #154. Will be merged alongside core changes.

### CODE REVIEW

**Comment by jkbpvsc** [comment]
I accidentally closed this one because I merged the `154-single-signer-add-bank-ix` branch.
Update this PR to merge to main and reopen it.

**Comment by jkbpvsc** [comment]
Also would probably be better to just modify the existing command to add the bank, by adding a `--with-seed` bool flag, the instruction handler should then search for a free address with canonical seeds.

**Comment by exdx** [comment]
> Also would probably be better to just modify the existing command to add the bank, by adding a `--with-seed` bool flag, the instruction handler should then search for a free address with canonical seeds.

Sure, totally agree. I'm working on that locally. Will push it up.

**Comment by exdx** [comment]
Reopening and targeting main

**Pull request closed without merging**
